<?php

return [
    /**
     * Alias Configuration for: Radion\\
     */
	'Radion\Cache' 								=> 		'Cache',
	'Radion\Config' 							=> 		'Config',
	'Radion\Database' 							=> 		'Database',
    'Radion\Debugger' 							=> 		'Debugger',
	'Radion\Viewer' 							=> 		'Viewer',
    'Radion\Service' 							=> 		'Service',
    'Radion\TimeTrackr' 						=> 		'TimeTrackr',
    
    /**
     * Alias Configuration for: Radion\\Http\\
     */
	'Radion\Router' 						    => 		'Router',
    'Radion\Request'						    => 		'Request',
    'Radion\Response' 						    => 		'Response',

    /**
     * Alias Configuration for: Radion\\DI\\
     */
    'Radion\App' 						    => 		'App',
    'Radion\Sharer' 						=> 		'Sharer',
    'Radion\Singleton'                      =>      'Singleton',
    
    /**
     * Alias Configuration for: Radion\\Service\\
     */
    'Radion\Service\ServiceContainer' 			=> 		'ServiceContainer',
    
    /**
     * Alias Configuration for: Composer Dependencies
     */
	'eftec\DocumentStoreOne\DocumentStoreOne'	=> 		'DocumentDB'
];
