<?php

return
[
  'enabled'   => true,

  /**
   * Illuminate Database Configuration
   * This is to start the connection for Illuminate Database System
   */
  'settings'  =>
  [
    'host'      => 'localhost',
    'driver'    => 'mysql',
    'database'  => 'pdemo',
    'username'  => 'root',
    'password'  => '',
    'port'      => '33006',
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
  ],
  
  /**
   * RadeBase Database Configuration
   * This is to start RadeBase Database Connection
   */
  'host'      => 'localhost',
  'driver'    => 'mysql',
  'database'  => 'pdemo',
  'username'  => 'root',
  'password'  => '',
  'port'      => '33006',
  'charset'   => 'utf8',
  'collation' => 'utf8_unicode_ci',
  'prefix'    => '',
];