<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Cookie Related Variables
    |--------------------------------------------------------------------------
    |
    | 'cookie_prefix' => Set a prefix if you need to avoid collisions
    | 'cookie_domain' => Set to .your-domain.com for site-wide cookies
    | 'cookie_path'   =>  Typically will be a forward slash
    | 'cookie_secure' =>  Cookies will only be set if a secure HTTPS connection exists.
    |
    */
    'cookie_prefix'	=> "",
    'cookie_domain'	=> "",
    'cookie_path'		=> "/",
    'cookie_secure'	=> FALSE,

    /*
    |--------------------------------------------------------------------------
    | Global XSS Filtering
    |--------------------------------------------------------------------------
    |
    | Determines whether the XSS filter is always active when GET, POST or
    | COOKIE data is encountered
    |
    */
    'global_xss_filtering' => TRUE,

];
?>